### PR TITLE
Removed Copright.

### PR DESCRIPTION
**Pull request by therealmrmuffin**
The Copyright Notice still disallows the license from being valid.

Close it if you don't want to change it.

### CODE REVIEW

**Comment by tijme** [comment]
Why does the copyright disallow this? As I read online; `Copyright is the legal term used to declare and prove who owns the intellectual property (the code, text, etc.). Licensing is the legal term used to describe the terms under which people are allowed to use the copyrighted material.`, which is exactly what the copyright/license currently states.

**Comment by therealmrmuffin** [comment]
> Why does the copyright disallow this? As I read online; `Copyright is the legal term used to declare and prove who owns the intellectual property (the code, text, etc.). Licensing is the legal term used to describe the terms under which people are allowed to use the copyrighted material.`, which is exactly what the copyright/license currently states.

Okay so, to clarify, when you put the copyright on a website without anything else it isn't valid because it doesn't point to a persons or legal entities name witch makes the copyright pretty much valid. Same here more the less, why do you see all of the open source type of licenses not mention a copyright mark. Well, they don't because indicating the  basically over rules any type of open source license that you have put in place that isn't singed by you and or the end user for that matter sometimes.

**Comment by therealmrmuffin** [comment]
> Why does the copyright disallow this? As I read online; `Copyright is the legal term used to declare and prove who owns the intellectual property (the code, text, etc.). Licensing is the legal term used to describe the terms under which people are allowed to use the copyrighted material.`, which is exactly what the copyright/license currently states.

Copyright should be mentioned first in the same sentence. Else it's disallowed because of standalone copyright markers and in the license and readme file it's self.

**Comment by tijme** [comment]
Fixed 🚀

**Pull request closed without merging**
